### ISSUE TITLE
VirtualBox 4.2.14 does not work on OSX - use 4.2.12 instead

### ISSUE THREAD

**Issue by mojolama** [rdickert/project-quicksilver#3]
Download it here:

https://www.virtualbox.org/wiki/Download_Old_Builds_4_2

See the comments here for more folks suffering with the same issue:

http://www.marshut.com/pzisi/progress-object-failure-ns-error-call-failed-when-running-vagrant-up-in-getting-started-guide.html

**Comment by rdickert** [comment]
Thanks for the heads-up! Hopefully they'll iron this out soon, but until then, anyone running VirtualBox should check this out.
