### ISSUE TITLE
 ImportError: No module named markup safe

### ISSUE THREAD

**Issue by davestacey** [rdickert/project-quicksilver#6]
I am close but stuck on:
"ImportError: No module named markup safe"
I tried to workaround manually by vagrant ssh and sudo easy_install jinja2 but no luck. - Thanks!

vagrant provision
[default] Running provisioner: ansible...
Traceback (most recent call last):
  File "/Users/webdev/Applications/ansible/bin/ansible-playbook", line 24, in <module>
    import ansible.playbook
  File "/Users/webdev/Applications/ansible/lib/ansible/playbook/**init**.py", line 18, in <module>
    import ansible.inventory
  File "/Users/webdev/Applications/ansible/lib/ansible/inventory/**init**.py", line 27, in <module>
    from ansible.inventory.script import InventoryScript
  File "/Users/webdev/Applications/ansible/lib/ansible/inventory/script.py", line 25, in <module>
    from ansible import utils
  File "/Users/webdev/Applications/ansible/lib/ansible/utils/**init**.py", line 29, in <module>
    from ansible.utils import template
  File "/Users/webdev/Applications/ansible/lib/ansible/utils/template.py", line 21, in <module>
    import jinja2
  File "/Library/Python/2.7/site-packages/jinja2/**init**.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 13, in <module>
    from jinja2 import nodes
  File "/Library/Python/2.7/site-packages/jinja2/nodes.py", line 18, in <module>
    from jinja2.utils import Markup
  File "/Library/Python/2.7/site-packages/jinja2/utils.py", line 520, in <module>
    from markupsafe import Markup, escape, soft_unicode
[error] ImportError: No module named markup safe

**Comment by rdickert** [comment]
It does look like you are close. After digging around, it looks like [Jinja has added a new dependency on the MarkupSafe package](http://jinja.pocoo.org/docs/intro/#markupsafe-dependency) since I installed it (I'm on version 2.6 - you can check your version by typing `pip freeze` in your terminal - at least for pip packages). Try running `sudo pip install markupsafe` or `sudo easy_install markupsafe`.

Side note: From what you said, it looks like you ran `sudo easy_install jinja2` on your vagrant-provisioned vm (after `vagrant ssh`). Any Ansible dependencies will need to be installed on your root machine - the one running Ansible - not the provisioning target (there will be no effect there, and anything you need on the target machine should be installed by Ansible). 

 Let me know if this works. If it does, I'll plan to update the docs. Thanks for trying out Project Quicksilver!

**Comment by davidopluslau** [comment]
Maybe it didn't help him/her, but it did help me. Thanks! :D

**Comment by rdickert** [comment]
Glad it helped!

**Comment by vivekraunak** [comment]
Hi
i have downloaded jinja2 from https://pypi.python.org/pypi/Jinja2
and put it in C:\Python27 location.
i am getting import error

> > > from jinja2 import Environment, FileSystemLoader
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "C:\Python27\jinja2__init__.py", line 33, in <module>
> > >     from jinja2.environment import Environment, Template
> > >   File "C:\Python27\jinja2\environment.py", line 13, in <module>
> > >     from jinja2 import nodes
> > >   File "C:\Python27\jinja2\nodes.py", line 18, in <module>
> > >     from jinja2.utils import Markup
> > >   File "C:\Python27\jinja2\utils.py", line 520, in <module>
> > >     from markupsafe import Markup, escape, soft_unicode
> > > ImportError: No module named markupsafe

could you please suggest what should i do to get markupsafe module.

**Comment by vivekraunak** [comment]
so it was very simple
i downloaded markupsafe from https://pypi.python.org/pypi/MarkupSafe and put it in https://pypi.python.org/pypi/Jinja2
and it worked!! :-)

**Comment by f31n** [comment]
helped me as well...
"pip install markupsafe"

**Comment by jussiheinonen** [comment]
'pip install markupsafe' did the job for me as well

**Comment by geerlingguy** [comment]
Same here, for some reason; I only ran into this after I had attempted to install ansible on a fresh Debian 8 VM and had forgotten to install `build-essential` prior to `pip install ansible`. The install failed during pycrypto install, and I ran into this error even after uninstalling and reinstalling Ansible.

**Comment by ejhw** [comment]
'pip install markupsafe' did not work for me. I had to download the markupsafe tarball and do `sudo python setup.py install` to install it.

**Comment by thechristian** [comment]
"sudo pip install markupsafe" worked for me

**Comment by mikeratnam** [comment]
The Markupsafe Version on your flask framework (pip freeze)  and the version in requirements.txt should be the same.

**Comment by cell13** [comment]
@ ejhw I solved the problem as your way. Thank you very much.

**Comment by bulught** [comment]
It surely did help me, Thanks!

**Comment by Lucantas** [comment]
I've tried rdickert's solution, with no success. But downloading the markupsafe tar ball did, thank you ejhw for the tip
